"""
Curation of the synthetic manifests generated by generate.py. A small model
gets a lot wrong, so we discard freely: we only keep what (1) parses as YAML
with valid apiVersion+kind, (2) passes kubeconform against the target
Kubernetes version, (3) contains no real secret (dataset/scanning.py), and
(4) is not a structural duplicate of another item in the batch or of the real
corpus (dataset/dedup.py). In hard-negative mode the secret check is
inverted: the item is only useful if it FOOLS a naive detector (regex/
entropy without dataset/scanning.py's refinements) while still being
considered clean by the real detector.

Usage:
    python -m generation.curate --mode rbac
    python -m generation.curate --mode hard-negative --corpus-hashes hashes.txt
"""

from __future__ import annotations

import argparse
import collections
import json
import subprocess
import sys
from pathlib import Path

import yaml

from dataset.dedup import skeleton_hash
from dataset.scanning import MIN_ENTROPY_BITS, MIN_LEN_FOR_ENTROPY, SENSITIVE_KEY_RE, find_secrets, shannon_entropy, walk_leaves

DEFAULT_K8S_VERSION = "1.29.0"


def parse_docs(manifest_yaml: str) -> list[dict] | None:
    try:
        docs = list(yaml.safe_load_all(manifest_yaml))
    except yaml.YAMLError:
        return None
    docs = [d for d in docs if isinstance(d, dict)]
    if not docs or not all("kind" in d and "apiVersion" in d for d in docs):
        return None
    return docs


def looks_suspicious_naive(docs: list[dict]) -> bool:
    """Deliberately naive version of the secret detector: key-name regex OR
    high entropy, with none of scanning.py's refinements (no placeholder
    allowlist, no path/URL/kebab-case-identifier exception). Represents what
    a simple scanner would trip on. Used only to validate that a
    hard-negative actually looks suspicious -- the real "is this a secret"
    call still belongs to find_secrets."""
    for doc in docs:
        for _path, key, value in walk_leaves(doc):
            if not isinstance(value, str) or not value:
                continue
            if SENSITIVE_KEY_RE.search(str(key)):
                return True
            if len(value) >= MIN_LEN_FOR_ENTROPY and shannon_entropy(value) >= MIN_ENTROPY_BITS:
                return True
    return False


def run_kubeconform(manifest_yaml: str, kubeconform_bin: str, k8s_version: str) -> tuple[bool, str]:
    try:
        proc = subprocess.run(
            [kubeconform_bin, "-summary", "-output", "json", "-kubernetes-version", k8s_version, "-"],
            input=manifest_yaml,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except FileNotFoundError:
        return False, "kubeconform_not_found"
    except subprocess.TimeoutExpired:
        return False, "kubeconform_timeout"

    try:
        report = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return False, "kubeconform_invalid_output"

    summary = report.get("summary", {})
    valid = summary.get("valid", 0)
    invalid = summary.get("invalid", 0)
    errors = summary.get("errors", 0)
    if valid > 0 and invalid == 0 and errors == 0:
        return True, "ok"
    return False, "kubeconform_invalid"


def curate_record(
    record: dict,
    seen_hashes: set[str],
    kubeconform_bin: str,
    k8s_version: str,
    skip_kubeconform: bool,
    corpus_hashes: set[str] | None,
) -> tuple[bool, str]:
    manifest_yaml = record.get("manifest_yaml", "")
    mode = record.get("mode", "base")

    docs = parse_docs(manifest_yaml)
    if docs is None:
        return False, "invalid_yaml"

    if not skip_kubeconform:
        ok, reason = run_kubeconform(manifest_yaml, kubeconform_bin, k8s_version)
        if not ok:
            return False, reason

    hits = [hit for doc in docs for hit in find_secrets(doc)]
    if mode == "hard-negative":
        if hits:
            return False, "real_secret_detected"
        if not any(looks_suspicious_naive([doc]) for doc in docs):
            return False, "hard_negative_not_suspicious"
    else:
        if hits:
            return False, "real_secret_detected"

    doc_hashes = [skeleton_hash(d) for d in docs]
    if any(h in seen_hashes for h in doc_hashes):
        return False, "structural_duplicate_in_batch"
    if corpus_hashes is not None and any(h in corpus_hashes for h in doc_hashes):
        return False, "structural_duplicate_in_corpus"

    seen_hashes.update(doc_hashes)
    return True, "ok"


def load_corpus_hashes(path: Path | None) -> set[str] | None:
    if path is None:
        return None
    return {line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()}


def curate(args: argparse.Namespace) -> dict:
    input_path = Path(args.input) if args.input else Path(f"generation/output/{args.mode}.jsonl")
    output_path = Path(args.output) if args.output else Path(f"generation/output/{args.mode}.curated.jsonl")
    corpus_hashes = load_corpus_hashes(Path(args.corpus_hashes) if args.corpus_hashes else None)

    seen_hashes: set[str] = set()
    reasons = collections.Counter()
    total = 0
    kept = 0

    with input_path.open("r", encoding="utf-8") as fh, output_path.open("w", encoding="utf-8") as out:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            total += 1
            ok, reason = curate_record(
                record, seen_hashes, args.kubeconform_bin, args.k8s_version, args.skip_kubeconform, corpus_hashes
            )
            reasons[reason] += 1
            if ok:
                kept += 1
                out.write(json.dumps(record, ensure_ascii=False) + "\n")

    pass_rate = kept / total if total else 0.0
    summary = {
        "mode": args.mode,
        "total": total,
        "kept": kept,
        "pass_rate": round(pass_rate, 4),
        "reject_reasons": dict(reasons.most_common()),
    }
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    if pass_rate < 0.5:
        print(
            f"\n[WARNING] pass rate ({pass_rate:.1%}) below 50% in mode '{args.mode}'. "
            "That usually points to a problem in the generation PROMPT, not the filter -- review generate.py.",
            file=sys.stderr,
        )
    print(f"\nCurated: {kept}/{total} written to {output_path}")
    return summary


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("base", "rbac", "hard-negative"), required=True)
    parser.add_argument("--input", default=None)
    parser.add_argument("--output", default=None)
    parser.add_argument("--corpus-hashes", default=None, help="file with one real-corpus skeleton_hash per line")
    parser.add_argument("--kubeconform-bin", default="kubeconform")
    parser.add_argument("--k8s-version", default=DEFAULT_K8S_VERSION)
    parser.add_argument("--skip-kubeconform", action="store_true")
    return parser.parse_args(argv)


def main(argv=None) -> None:
    args = parse_args(argv)
    curate(args)


if __name__ == "__main__":
    main()
